priority_companies:
  - "NVIDIA"
  - "Intel"
  - "Google"
  - "Microsoft"
  - "Amazon"
  - "Meta"
  - "Apple"
  - "Mobileye"
  - "Qualcomm"
  - "Palo Alto Networks"
  - "Check Point"

regular_companies:
  - "Wix"
  - "Monday.com"
  - "Amdocs"
  - "Tower Semiconductor"
  - "Cadence"
  - "Synopsys"
  - "Cisco"
  - "Samsung"
  - "Applied Materials"
  - "Western Digital"
  - "Broadcom"
  - "Arm"
  - "Akamai"
  - "CyberArk"
  - "Varonis"
  - "Nice"
  - "Fiverr"
  - "Gett"

defense_companies:
  - "IAI"
  - "Rafael"
  - "Elbit"

locations:
  - "Tel Aviv"
  - "Herzliya"
  - "Raanana"
  - "Rehovot"
  - "Petah Tikva"
  - "Rishon LeZion"
  - "Holon"
  - "Kfar Saba"

hours_active_start: 8
hours_active_end: 22
hours_old: 72
