priority_companies:
  - "NVIDIA"
  - "Intel"
  - "Google"
  - "Microsoft"
  - "Amazon"
  - "Meta"
  - "Apple"
  - "Mobileye"
  - "Qualcomm"
  - "Palo Alto Networks"
  - "Check Point"

regular_companies:
  - "Wix"
  - "Monday.com"
  - "Amdocs"
  - "Tower Semiconductor"
  - "Cadence"
  - "Synopsys"
  - "Cisco"
  - "Samsung"
  - "Applied Materials"
  - "Western Digital"
  - "Broadcom"
  - "Arm"
  - "Akamai"
  - "CyberArk"
  - "Varonis"
  - "Nice"
  - "Fiverr"
  - "Gett"
  - "Wiz"
  - "Snyk"
  - "Taboola"
  - "Imperva"
  - "Outbrain"
  - "IronSource"
  - "Kaltura"

defense_companies:
  - "IAI"
  - "Rafael"
  - "Elbit"

locations:
  - "Tel Aviv"
  - "Herzliya"
  - "Raanana"
  - "Rehovot"
  - "Petah Tikva"
  - "Rishon LeZion"
  - "Holon"
  - "Kfar Saba"

workday_companies:
  - name: "NVIDIA"
    url: "https://nvidia.wd5.myworkdayjobs.com/wday/cxs/nvidia/NVIDIAExternalCareerSite/jobs"
    base_url: "https://nvidia.wd5.myworkdayjobs.com"
    special_locations:
      - "Israel"
  - name: "Intel"
    url: "https://intel.wd1.myworkdayjobs.com/wday/cxs/intel/External/jobs"
    base_url: "https://intel.wd1.myworkdayjobs.com"

smartrecruiters_companies:
  - name: "Monday.com"
    id: "MondayComLtd"
  - name: "Wix"
    id: "Wix"
  - name: "CyberArk"
    id: "CyberArkSoftware"
  - name: "Check Point"
    id: "CheckPointSoftwareTechnologies"
  - name: "Mobileye"
    id: "Mobileye"
  - name: "Palo Alto Networks"
    id: "PaloAltoNetworks"
  - name: "Qualcomm"
    id: "qualcomm"
  - name: "Samsung"
    id: "samsungelectronics"
  - name: "Cisco"
    id: "cisco"
  - name: "Broadcom"
    id: "broadcom"
  - name: "Arm"
    id: "arm"
  - name: "Akamai"
    id: "akamai"
  - name: "Varonis"
    id: "varonis"
  - name: "Gett"
    id: "gett"
  - name: "Tower Semiconductor"
    id: "towersemiconductor"
  - name: "Amdocs"
    id: "amdocs"
  - name: "Synopsys"
    id: "synopsys"
  - name: "Apple"
    id: "apple"
  - name: "Google"
    id: "google"
  - name: "Microsoft"
    id: "microsoft"
  - name: "Fiverr"
    id: "fiverr"
  - name: "Cadence"
    id: "cadencedesign"
  - name: "Outbrain"
    id: "Outbrain"
  - name: "IronSource"
    id: "ironSource"

greenhouse_companies:
  - name: "Nice"
    id: "nice"
  - name: "Wiz"
    id: "wizinc"
  - name: "Taboola"
    id: "taboola"

hours_active_start: 5
hours_active_end: 19
hours_old: 72
